# Generated by Django 4.2.6 on 2023-12-16 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_gate',
            options={'ordering': ['id'], 'verbose_name': 'Модели ворот', 'verbose_name_plural': 'Модели ворот'},
        ),
        migrations.AlterModelOptions(
            name='type_gate',
            options={'ordering': ['id'], 'verbose_name': 'Тип ворот', 'verbose_name_plural': 'Типы ворот'},
        ),
    ]
